<?php
// 3.2.5 - documentation-of added for languages requiring it
// for English is identical to documentation
// 3.2.6 - txtNoHosts
// 3.2.8 - phpNotExists - txtProjectsLink -	phpExtensions - phpVersionsUse
// 3.3.0 - txtPathNoSlash
// 3.3.2 - txtSlashEnd
// 3.3.7 - apacheLoadedModules

$langues = array(
	'langue' => 'Deutsch',
	'locale' => 'german',
	'titreHtml' => 'WAMPSERVER-Homepage',
	'titreConf' => 'Server-Konfiguration',
	'versa' => 'Apache-Version:',
	'doca2.2' => 'httpd.apache.org/docs/2.2/de/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/de/',
	'versp' => 'PHP-Version:',
	'server' => 'Server-Software:',
	'documentation' => 'Dokumentation',
	'documentation-of' => 'Dokumentation zu',
	'docp' => 'https://www.php.net/manual/de/',
	'versm' => 'MySQL-Version:',
	'docm' => 'https://dev.mysql.com/doc/',
	'versmaria' => 'MariaDB-Version: ',
	'docmaria' => 'https://mariadb.com/docs/server',
	'phpExt' => 'Geladene Erweiterungen: ',
	'titrePage' => 'Werkzeuge',
	'txtProjet' => 'Projekte',
	'txtNoProjet' => 'Noch keine Projekte.<br />Um ein neues Projekt zu erstellen, einfach ein Verzeichnis in „www“ erstellen.',
	'txtProjects' => 'Ordner in %s<br />Um sie als HTTP-Link zu nutzen, muss erst ein VirtualHost erstellt werden.',
	'txtProjectsLink' =>'Es funktioniert auch: Rechtsklick, Einstellungen, Caution: Risky …, Allow links on projects …',
	'txtAlias' => 'Aktuelle Aliases',
	'txtNoAlias' => 'Bisher kein Alias.<br />Zum Erstellen, das WAMPSERVER-Menü nutzen.',
	'txtVhost' => 'Aktuelle VirtualHosts',
	'txtServerName' => 'Server-Name %s hat einen Syntax-Fehler in Datei %s.',
	'txtDocRoot' => 'Server-Name %s nutzt DocumentRoot %s. Dies ist reserviert für localhost.',
	'txtTLDdev' => 'Server-Name %s nutzt TLD %s. Dies wird von Web-Browsern genutzt. Andere TLD nutzen (.test zum Beispiel).',
	'txtNoHosts' => 'Server-Name %s ist nicht in der Host-Datei definiert.',
	'txtServerNameIp' => 'IP %s für Server-Name %s stimmt nicht mit Datei %s überein.',
	'txtVhostNotClean' => 'Die Datei %s wurde nicht bereinigt. Es verbleiben Beispieldateien wie: dummy-host.example.com',
	'txtNoVhost' => 'Kein VirtualHost erstellt. Jedes Projekt in Datei: wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf hinzufügen',
	'txtNoIncVhost' => 'Auskommentieren oder hinzufügen von <i>Include conf/extra/httpd-vhosts.conf</i> in Datei wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => 'Die Datei: %s existiert nicht.',
	'txtNoPath' => 'Der Pfad %s für %s existiert nicht. (Datei: %s)',
	'txtSlashEnd' => 'Der Pfad %s für %s wurde mit einem Schrägstrich beendet. (Datei: %s)',
	'txtPathNoSlash' => 'Der Pfad %s für %s wurde nicht mit einem Schrägstrich / beendet. (Datei: %s)',
	'txtNotWritable' => 'Die Datei: %s ist nicht beschreibbar.',
	'txtNbNotEqual' => 'Die Anzahl von %s stimmt nicht mit der Anzahl von %s in Datei %s überein.',
	'txtAddVhost' => 'Einen VirtualHost hinzufügen',
	'txtPortNumber' => 'Port-Nummer für %s hat einen falschen Wert oder ist nicht gleich Datei %s.',
	'txtCorrected' => 'Einige VirtualHosts-Fehler konnten korrigiert werden.',
	'forum' => 'Wampserver-Forum',
	'forumLink' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Für Apache definerter Port: ',
	'mysqlportUsed' => 'Für MySQL definierter Port: ',
	'mariaportUsed' => 'Für MariaDB definerter Port: ',
	'defaultDBMS' => 'Standard DBMS',
	'phpNotExists' => 'PHP-Version existiert nicht.',
	'HelpMySQLMariaDB' => 'Wie wird MySQL und/oder MariaDB genutzt?<br>Was ist Standard DBMS?<br>Wie wird Standard DBMS geändert?<br>Passende Hilfe: Rechtsklick Wampmanager-Icon -> Hilfe -> Help MariaDB - MySQL',
	'nolocalhost' => 'Es ist keine gute Idee localhost in der URL von startenden Projekten zu nutzen. Es ist besser einen VirtualHost zu definieren in der Datei <br />wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br /> und nicht localhost in der URL zu nutzen.',
	'phpExtensions' => 'Geladene PHP-Erweiterungen',
	'phpVersionsUse' => 'Verwendete PHP-Versionen',
	'apacheLoadedModules' => 'Geladene Apache-Module',
	);
?>
